test_project:
  outputs:
    dev:
      dbname: test_db
      host: localhost
      pass: test123
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
