
version: 2

models:
  - name: sales_summary_by_customer
    description: "Sales summary by customer"
    columns:
      - name: customer_id
        description: "The unique identifier for the customer"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "The name of the customer"
      - name: total_sales
        description: "Total sales amount for the customer"
      - name: total_discount
        description: "Total discount amount applied to the customer's orders"
      - name: total_quantity_purchased
        description: "Total quantity of products purchased by the customer"

  - name: sales_summary_by_date
    description: "Sales summary by date"
    columns:
      - name: order_date
        description: "The date on which the orders were placed"
        tests:
          - not_null
      - name: total_sales
        description: "Total sales amount on this date"
      - name: total_discount
        description: "Total discount amount applied on this date"
      - name: total_quantity_sold
        description: "Total quantity of products sold on this date"
